<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/07/26 14:37:42
sfConfig::add(array(
  'mod_recruitmentapply_enabled' => true,
  'mod_recruitmentapply_view_class' => 'sfPHP',
));
